### ISSUE TITLE
Support for inlines in fieldsets

### ISSUE THREAD

**Issue by manelclos** [fusionbox/django-betterforms#25]
Is this possible using django-betterforms?

**Comment by rockymeza** [comment]
Hi!

Getting on a plane right now, but have you looked at MultiForm, that might
be what you are looking for.

-Rocky Meza
2015年4月9日 上午10:56于 "Manel Clos" <notifications@github.com>写道：

**Comment by pipermerriam** [comment]
Can elaborate on your question a bit.  What are you trying to accomplish.

**Comment by manelclos** [comment]
Hi, with plain django admin it is not possible to mix the "inlines" in the fieldsets. All inlines come at end. I was wondering if something similar is possible (and easy) with betterforms as I found it could in some web page, but I was unable to find how when reading the documentation.

**Comment by rockymeza** [comment]
Hi @manelclos,

We currently don't have anything for overriding how the admin works. If you are trying to do something with inline formsets outside of the admin, you could check out [MultiForm](https://django-betterforms.readthedocs.org/en/latest/multiform.html), but I don't think that it will really work in the admin center.

**Comment by manelclos** [comment]
Ok, thanks!
