### ISSUE TITLE
Multiple instances of the same form

### ISSUE THREAD

**Issue by tyteen4a03** [fusionbox/django-betterforms#26]
It seems like this plugin is not designed to work well with multiple instances of the same form on the same page. It relies on IDs which makes the page's markup invalid if more than one instance of a form exist.

(Heck, even two forms that happen to share the same field name would make the page invalid HTML as well)

**Comment by acatton** [comment]
Hello @tyteen4a03,

Thank you for your bug report. However it sounds like the default Django behavior. This is why [Django recommends to use prefixes when two forms are on the same page](https://docs.djangoproject.com/en/dev/ref/forms/api/#prefixes-for-forms). Have you tried to use prefixes with betterforms?
