### ISSUE TITLE
Showing single form fields doesn't work

### ISSUE THREAD

**Issue by c0d3z3r0** [fusionbox/django-betterforms#36]
I'm trying to view two ModelForms through MultiModelForm with a FormView.
In the template I can't view single fields using e.g. `{{ form.username }}` while using a loop like below works.

~~~
{% for field in form %}
  {{ field }}
{% endfor %}
~~~

Edit:
{{ form.user.username }} works. Is this intended?

**Comment by c0d3z3r0** [comment]
I modified __getitem__ in the MultiForm class but that only works for two forms with unique field names.

~~~
def __getitem__(self, key):
        try:
            return self.forms[key]
        except KeyError:
            for form in self.forms.keys():
                if key in self.forms[form].fields.keys():
                    return self.forms[form][key]
        raise KeyError
~~~

**Comment by c0d3z3r0** [comment]
My solutions raises more problems... maybe that was a bad idea ;)

**Comment by julianandrews** [comment]
> {{ form.user.username }} works. Is this intended?

Yup, it sounds as if you're worked this all out. For fine grained access to fields the `{{ form.user.username }}` approach is the the intended approach. Direct access to fields causes problems if forms share field names.

I'm going to go ahead and close the bug!

**Comment by rockymeza** [comment]
Perhaps some documentation might help here?

-rocky
2015年10月12日 上午3:39，"Julian Andrews" <notifications@github.com>写道：

**Comment by julianandrews** [comment]
I was thinking about that. The docs do have a snippet that describes this  in a view context, which sort of implies the use in templates" 

    form = UserProfileMultiForm()
    # get the Field object
    form['user'].fields['name']
    # get the BoundField object
    form['user']['name']

But possibly that section could be fleshed out to include a short template example to make it really explicit.
