### ISSUE TITLE
kwargs.update ruining use of MultiForm with UpdateView

### ISSUE THREAD

**Issue by proph73** [fusionbox/django-betterforms#38]
No problem using your lib with CreateView. Saved me time, thank you guys. But following http://django-betterforms.readthedocs.org/en/latest/multiform.html for DetailView did not make it.

All details on [stackoverflow](http://stackoverflow.com/q/34725482/3949615).

**Comment by rockymeza** [comment]
Hi! Sorry that you ran into a problem, could you please provide a stack
trace?

Thanks,
-rocky
2016年1月11日 下午11:46於 "proph73" <notifications@github.com>寫道：

No problem using your lib with CreateView Saved me time, thank you guys But
following http://django-betterformsreadthedocsorg/en/latest/multiformhtml
for DetailView did not make it

All details on stackoverflow <http://stackoverflowcom/q/34725482/3949615>

—
Reply to this email directly or view it on GitHub
<https://github.com/fusionbox/django-betterforms/issues/38>.

**Comment by proph73** [comment]
Hello ! Thanks for he answer.
First, could my problem be because I am using Python3 ?
I am not sure about what you are asking : "stack trace". Does this joined
file do ?
BG



2016-01-12 0:21 GMT+01:00 Rocky Meza <notifications@github.com>:

**Comment by rockymeza** [comment]
Hi @proph73,

I think you were trying to attach a file to the github issue, unfortunately GitHub doesn't support attachments. Can you paste in what you were trying to send?

**Comment by proph73** [comment]
Here's the html of the error : http://pastebin.com/Hmrmg2qN
<http://pastebin.com/Hmrmg2qN>

2016-01-12 2:47 GMT+01:00 Rocky Meza <notifications@github.com>:

**Comment by rockymeza** [comment]
You need to use MultiModelForm instead of MultiForm.

**Comment by proph73** [comment]
I am confused...
:D Thank you very much, that was stupid of me. It seems to work.

2016-01-12 3:46 GMT+01:00 Rocky Meza <notifications@github.com>:

**Comment by rockymeza** [comment]
You are not stupid! Thanks for using betterforms! Let us know if you have
any other questions!

-rocky
2016年1月12日 下午5:48於 "proph73" <notifications@github.com>寫道：
