### ISSUE TITLE
No input fields rendering with MultiModelForm

### ISSUE THREAD

**Issue by AJLivine** [fusionbox/django-betterforms#40]
Hi,

I'm having an issue with input fields not rendering for a MultiModelForm. Here's my forms.py:

```python
# forms.py
from django import forms
from betterforms.multiform import MultiModelForm
from .models import Person, Alias, PrimaryEmailAddress


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('last_name', 'middle_name_or_initial', 'first_name')


class PrimaryEmailAddressForm(forms.ModelForm):
    class Meta:
        model = PrimaryEmailAddress
        fields = ('email_address',)


class AliasForm(forms.ModelForm):
    class Meta:
        model = Alias
        fields = ('alias',)


class PersonMultiForm(MultiModelForm):
    form_class = {
        'person': PersonForm,
        'primary_email': PrimaryEmailAddressForm,
        'alias': AliasForm
    }

    def save(self, commit=True):
        objects = super(PersonMultiForm, self).save(commit=False)

        if commit:
            person = objects['person']
            person.save()
            primary_email = objects['primary_email']
            primary_email.person = objects['primary_email']
            alias = objects['alias']
            alias.person = person

        return objects
```

Here's my template:

```html
<!--add_person.html-->
<form action="" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
```

And here's my views.py:

```python
# views.py
from django.views.generic import CreateView
from .forms import PersonForm, PersonMultiForm
from .models import Person, PrimaryEmailAddress, Alias


class CreatePerson(CreateView):
    form_class = PersonMultiForm
    template_name = 'add_person.html'
```

The result doesn't render any of the input fields:
![image](https://cloud.githubusercontent.com/assets/12123585/13359961/b4aba912-dc84-11e5-8e1f-c2bbf6aee43d.png)

However, when I change the line `form_class = PersonMultiForm` in my views.py to `form_class = PersonForm`, the form renders properly:
![image](https://cloud.githubusercontent.com/assets/12123585/13359993/e5a797a6-dc84-11e5-826a-74591b03a165.png)

I'm new to Django, so it's quite possible I'm doing Django wrong, not using MultiModelForm wrong.

Any help would be appreciated!

**Comment by rockymeza** [comment]
Hi @AJLivine,

This definitely looks like a weird problem. If you do the following in a shell, what happens?

```python
>>> form = PersonMultiForm()
>>> form.as_p()
```

**Comment by AJLivine** [comment]
I'm so embarrassed. Specifying multiple key, value pairs in PersonMultiForm's "form_**class**" variable certainly wouldn't get me what I want. Works in shell and renders properly when changed to "form_**classes**".

Thanks for your response!

I only hope this issue can provide guidance for other typo-prone folks.

**Comment by rockymeza** [comment]
Oh yes, I didn't see that either. Haha. I was worried that as_p was broken,
because I rarely use it. Good to know it's still working.

-rocky
2016年2月29日 上午3:18於 "AJ Livine" <notifications@github.com>寫道：
