### ISSUE TITLE
can't set attribute cleaned_data in form clean method

### ISSUE THREAD

**Issue by truhlik** [fusionbox/django-betterforms#41]
Django Version: 1.9.4
Python Version: 2.7.6

After submit empty form I am getting this error:

> File "/home/truhlik/.virtualenvs/reality/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
>   88.         return handler(request, *args, **kwargs)
> 
> File "/home/truhlik/.virtualenvs/reality/local/lib/python2.7/site-packages/django/views/generic/edit.py" in post
>   256.         return super(BaseCreateView, self).post(request, *args, **kwargs)
> 
> File "/home/truhlik/.virtualenvs/reality/local/lib/python2.7/site-packages/django/views/generic/edit.py" in post
>   221.         if form.is_valid():
> 
> File "/home/truhlik/.virtualenvs/reality/local/lib/python2.7/site-packages/betterforms/multiform.py" in is_valid
>   99.                     self.forms[key].cleaned_data = data
> 
> Exception Type: AttributeError at /backend/opportunities/create/
> Exception Value: can't set attribute

I check in debug mode that the form is correct, the key is correct and the cleaned_data attribute exists. So it looks like .cleaned_data would be read only attribute.
Have any idea what's going on there?

**Comment by rockymeza** [comment]
hi @truhlik,

what are your form_classes?

**Comment by truhlik** [comment]
File with forms attached. Seems that problem appears only if one of the forms is Formset.

[forms.txt](https://github.com/fusionbox/django-betterforms/files/180207/forms.txt)

**Comment by rockymeza** [comment]
@gavinwahl I think you broke this in be4e807817292092022ceafa988d55c4e0e428f3

**Comment by rockymeza** [comment]
This prevents using formsets with MultiForm, see #43

**Comment by rockymeza** [comment]
Hi, I have just opened #44 with a possible fix. If anybody is encountering this bug, please try it out.

**Comment by truhlik** [comment]
@rockymeza I can confirm, that the original issue is fixed by this commit.

**Comment by Atorich** [comment]
So, when it will be released?

**Comment by Atorich** [comment]
Fix for this issue is not released yet, thus betterforms installed via pip is still broken.

**Comment by decolens** [comment]
When will it be fixed on pip?
