### ISSUE TITLE
How can use form_class with extra fields

### ISSUE THREAD

**Issue by flaudizio** [fusionbox/django-betterforms#43]
Hi, 

with betterforms can possible to use form_classes with more one field (like extra from inlineformset_factory) ?

Thank's a lot.

**Comment by rockymeza** [comment]
Hi @flaudizio,

Are you talking about MultiForm?

You can use an a FormSet inside of a MultiForm. There is an example of using an inline formset inside of a MultiForm in the tests: https://github.com/fusionbox/django-betterforms/blob/master/tests/forms.py#L129-L146

Is that what you were thinking?

**Comment by flaudizio** [comment]
Hi, thank's a lot.

One else thing, when I save in view I get this error:

can't set attribute

multiform.py in is_valid:


   1.

           try:

   2.

               cleaned_data = self.clean()

   3.

           except ValidationError as e:

   4.

               self.add_crossform_error(e)

   5.

           else:

   6.

               if cleaned_data is not None:

   7.

                   for key, data in cleaned_data.items():



   1.

                       self.forms[key].cleaned_data = data

   ...


   1.

           return forms_valid and not self.crossform_errors

   2.

   3.

       def non_field_errors(self):

   4.

           form_errors = (

   5.

               form.non_field_errors() for form in self.forms.values()

   6.

               if hasattr(form, 'non_field_errors')



*My forms.py*


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name']

class PhoneForm(ModelForm):
    class Meta:
        model = Phone
        fields = ['number']

PhoneInlineFormSet = inlineformset_factory(Contact, Phone,
fields=('number',), extra=3)

class ContactPhoneForm(MultiModelForm):
    form_classes = {
        'contato': ContactForm,
        'telefone': PhoneInlineFormSet,

    }

    def __init__(self, *args, **kwargs):
        instance = kwargs.pop('instance', None)
        if instance is not None:
            kwargs['instance'] = {
                'contact': instance,
                'phone': instance,
            }
        super(ContactPhoneForm, self).__init__(*args, **kwargs)

*In my views.py*

class ContactCreate(CreateView):
    form_class = ContatoTelefoneForm
    template_name = "forms/contato.html"
    success_url = reverse_lazy('home')
    success_message = "Contato cadastro com sucesso."

    def form_valid(self, form):

        contato = form['contact'].save()
        telefone = form['phone'].save(commit=False)

        telefone.contato = contato
        telefone.save()

        return super(ContactCreate, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.success_url
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to

Once again, very thank you.

Atenciosamente,
Flaudizio B. S. Filho
82.8809.4382 (OI)
82.9662.3482 (TIM)

**Comment by rockymeza** [comment]
Oh darn, I think you are running into the #41 bug. I'm going to close this bug in favor of that one. I think perhaps I have a solution for it in the #44 PR.

**Comment by flaudizio** [comment]
Hi,

can you show the example using inline ? 

I just haven't this (in view):

AttributeError
'list' object has no attribute 'contato'

contato = form['contato'].save()
telefone = form['telefone'].save(commit=False)
telefone.contato = contato
telefone.save()

Thank's and sorry for work.
