### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jpic** [fusionbox/django-betterforms#52]
Hello,

It seems last release is from 2016, is it possible to make a new release ?

Thanks

**Comment by jxcl** [comment]
To do a release we usually like to make sure that the tests are running on the currently supported versions of Django. I don't really have the time to do that myself at the moment, but a PR for that would be wonderful. 

I don't believe we have anything set up for accepting donations for this project, sorry!

**Comment by jeromelebleu** [comment]
> To do a release we usually like to make sure that the tests are running on the currently supported versions of Django. I don't really have the time to do that myself at the moment, but a PR for that would be wonderful.

I've updated testing and fixed tests for lasts Django versions - e.g. 1.11 & 2.0 - in #54.

**Comment by jxcl** [comment]
django-betterforms 1.2 is released! Thank you for your help!
