### ISSUE TITLE
"Newline not allowed" when installing the package. Setuptools won't allow multiline descriptions anymore.

### ISSUE THREAD

**Issue by Ekozmaster** [fusionbox/django-betterforms#65]
Our CI isn't able to run anymore due to not being able to install `django-betterforms==1.2`.

Since November 10th, 2021, setuptools won't allow the parameter `description`, given to `setuptools.setup()` to have multiple lines, due to some [malformed PKG-INFO parsing](https://github.com/pypa/setuptools/issues/1390)

[The fix](https://github.com/pypa/setuptools/pull/2870/files) rolled out 4 days ago, which ended up breaking the package's setup script.

**Comment by CSprat451** [comment]
Fixed in #67
